### ISSUE TITLE
network.interfaces() breaks with nettools 2.10-alpha on debian 10.10

### ISSUE THREAD

**Issue by justinschw** [FGRibreau/network-config#38]
Here is the code I use, and the error output.
```
> const netconfig = require('network-config');
undefined
> netconfig.interfaces((err, stdout) => { console.log(err); console.log(stdout); });
undefined
> Uncaught TypeError: Cannot read property '1' of null
    at getInterfaceIpAddr (/home/jusschwa/Documents/dev/guardian-network/node_modules/network-config/src/ifconfig.interfaces.js:132:15)
    at /home/jusschwa/Documents/dev/guardian-network/node_modules/network-config/src/ifconfig.interfaces.js:65:11
    at Array.map (<anonymous>)
    at parse (/home/jusschwa/Documents/dev/guardian-network/node_modules/network-config/src/ifconfig.interfaces.js:51:43)
    at /home/jusschwa/Documents/dev/guardian-network/node_modules/network-config/src/ifconfig.interfaces.js:42:17
    at ChildProcess.exithandler (node:child_process:388:7)
    at ChildProcess.emit (node:events:394:28)
    at ChildProcess.emit (node:domain:532:15)
    at maybeClose (node:internal/child_process:1067:16)
>
```

Version Info:
```
# ifconfig --version
net-tools 2.10-alpha
# cat /etc/debian_version 
10.10
# uname -a
Linux spring-forest 4.19.0-17-amd64 #1 SMP Debian 4.19.194-2 (2021-06-21) x86_64 GNU/Linux
```

**Comment by justinschw** [comment]
Sorry, upon further investigation this is a dupe of #34. Working on a PR now.
